### ISSUE TITLE
Replace deprecated functions

### ISSUE THREAD

**Issue by elm** [elm/Roundcube-SMTP-per-Identity-Plugin#15]
> [01-Jun-2016 00:03:14 +0200]: <dmm112qt> Warning: Call to deprecated function write_log(); See bc.inc for replacement
> [01-Jun-2016 00:03:45 +0200]: <dmm112qt> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement

**Comment by Gr4ffy** [comment]
`
[01-Jun-2016 15:38:08 +0200]: <9r7dod75> Warning: Call to deprecated function get_table_name(); See bc.inc for replacement`
`[01-Jun-2016 15:38:08 +0200]: <9r7dod75> Warning: Call to deprecated function rep_specialchars_output(); See bc.inc for replacement
`

**Comment by elm** [comment]
These called are not from this plugin. Or I cannot find where they are :)

**Comment by Gr4ffy** [comment]
Sorry for misunderstanding, this is probably log from "Filters" plugin.

**Comment by elm** [comment]
Closed by 40b5803e255f7de165feeeeeeb73ec085f23781e
