### ISSUE TITLE
Explain usage for encrypted Connection

### ISSUE THREAD

**Issue by sahne123** [elm/Roundcube-SMTP-per-Identity-Plugin#9]
Since there is no checkbox for choosing SSL/TLS Encryption i thought it might be chosen based on the standard Ports. I figured out, that the syntax tsl://host, ssl://host is needed and right now i realized there is an example in the readme.

To clear this out, it would be good to clarify this with the label. If you agree with that a can make a pull-request by my own.

**Comment by elm** [comment]
You're welcome to open a pul request :) The settings for an identity are the same that are used in the roundcube config. See https://github.com/roundcube/roundcubemail/blob/8b25622c75e742a8e4febfb2e4d248e916eeee00/config/config.inc.php.sample#L41-L51

**Comment by elm** [comment]
Closed by #10
